### ISSUE TITLE
A little typo

### ISSUE THREAD

**Issue by UnAfraid** [Reefstah/TelegramBotAPI#1]
Hello,

I started using your API today and i've notice small typo

```
List<BasicNameValuePair> fields = disable_web_page_preview.map(preview -> Arrays.asList(new BasicNameValuePair("disable_web_page_preview", preview.toString()), new BasicNameValuePair("text", text))).orElseGet(() -> Collections.emptyList());
```

the text property is not assigned unless disable_web_page_preview is set.

Also the Chat interface seems to not have getId() method declared.

Thanks!

**Comment by reefstah** [comment]
Thank you for using the API and the issue report. 
Might have been to quick with refactoring.
Should be good now. 
I will check the rest tomorrow.

Good luck on your bot!

**Comment by reefstah** [comment]
Ah, I see your fork now will look to merge tomorrow.

**Comment by UnAfraid** [comment]
I removed the fork since u fixed all issues i don't need it anymore, thanks!
